name: imaging
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - ipykernel
  - pytorch
  - torchvision
  - matplotlib
  - pandas
  - openpyxl
  - scikit-image
  - scikit-learn
  - seaborn
  - ipyfilechooser
  - cellpose
  - statannotations 
  - nd2
  - cellpose
  - aicsimageio[all]
  
